name: evefrontier
description: Open-source collection of Dart & Flutter packages and tools designed for developers and players of the EVE Frontier game.
homepage: https://dip.dev
issue_tracker: https://github.com/dip-develop/evefrontier/issues
repository: https://github.com/dip-develop/evefrontier
publish_to: none

funding:
  - https://www.buymeacoffee.com/dip.dev
  - https://www.thanks.dev/dip-dev-info

environment:
  sdk: ^3.6.0

workspace:
  - packages/api
  - apps/tools

dev_dependencies:
  melos: ^7.0.0-dev.9

melos:
  version:
    linkToCommits: true
    changelog: true
    workspaceChangelog: true
    git:
      requireCleanWorkingDir: true
      tagPrefix: ''
      tagNameTemplate: '{package}-v{version}'
  
  publish:
    yes: true
    prepublish:
      - dart test
  
  scripts:
    lint:all:
      run: melos run analyze-ci && melos run format-ci
      description: Run all static analysis checks.
    bootstrap:
      run: melos bootstrap --no-scripts
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build -d
    format:
      run: melos exec -- "dart format ."
    analyze:
      run: melos exec -- "dart analyze ."
    test:
      run: melos exec -- "dart test"
    lint:
      run: melos exec -- "flutter analyze --no-fatal-infos"
